platform :ios, '9.0'

use_frameworks!

install! 'cocoapods',
  :disable_input_output_paths => true,
  :share_schemes_for_development_pods => true

target 'CleanJSON_Example' do
  pod 'CleanJSON', :path => '../'

  target 'CleanJSON_Tests' do
    inherit! :search_paths

    
  end
end
