# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # 查找 podspec 文件路径
  def find_podspec_path
    # 读取所有 podspec 文件
    files = Dir.glob(["../*.podspec"])

    if files.empty?
      raise "Couldn't found podspec file."
    end

    return File.basename(files[0])
  end

  desc "unit test"
  lane :test do
  	scan(
    	workspace: "Example/CleanJSON.xcworkspace", 
    	scheme: "CleanJSON_Tests", 
    	devices: ["iPhone SE"])
  	UI.message("Test Succeeded")
  end

  desc "release new version"
  lane :release do |options|
    target_version = options[:version]
    raise "The version is missed." if target_version.nil?

    scan(
    	workspace: "Example/CleanJSON.xcworkspace", 
    	scheme: "CleanJSON_Tests", 
    	devices: ["iPhone SE"])

    # carthage 打包
    carthage(
      command: "build",
      platform: "iOS", 
      use_binaries: true,
      no_skip_current: true)

    # 获取源码 podspec 文件路径
    podspec_path = find_podspec_path()

    # 设置 podspec 版本
    version_bump_podspec(
    	path: podspec_path, 
    	version_number: target_version)

    # 获取 podspec 名称
    podspec_name = podspec_path.chomp(".podspec")

    paths = [podspec_path, "./fastlane", "Carthage/Build/iOS/Static/#{podspec_name}.framework"]

    git_add(path: paths)

    git_commit(
      path: paths, 
      message: "release #{target_version} version")
    
    add_git_tag tag: target_version
    push_to_git_remote

    pod_push
  end

end
